version : '3'

services:
  chat-backend: 
    image: chat-backend
    build: 
      context: ./Nodejs
    image: nodejs
    depends_on:
      - mongo
    networks:
      - chatapp
  
  chat-frontend:
    image: chat-frontend
    build:
      context: ./chat
    image: reactjs
    depends_on:
      - chat-backend
    networks:
      - chatapp
  
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'dinesh'
      MONGO_INITDB_ROOT_PASSWORD: 'dinesh'
      MONGO_INITDB_HOST: 'mongo'
    networks:
      - chatapp

  ngnix:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chat-frontend
      - chat-backend
    ports:
      - "80:80"
      - "4200:4200"
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - chatapp
networks:
  chatapp: