version : '3'

services:
  chat-backend: 
    build: 
      context: ./Nodejs
    image: nodejs
    restart: always
    ports:
      - '4200:4200'
    links: 
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'dinesh'
      MONGO_INITDB_ROOT_PASSWORD: 'dinesh'
      MONGO_INITDB_HOST: 'mongo'
  
  chat-frontend:
    build:
      context: ./chat
    image: reactjs
    restart: always
    ports: 
      - '80:80'
    depends_on:
      - chat-backend